### PR TITLE
PALLADIO-528: fixing the layout of the usage model diagrams.

### PR DESCRIPTION
**Pull request by mazkatli**

### CODE REVIEW

**Comment by mazkatli** [comment]
look at PALLADIO-528 ticket.

**Review by seiferma — CHANGES_REQUESTED** [review]
There are still some usage models broken:
* CloudStore
  * HomeInteraction.usagemodel
  * OrderingMix.usagemodel
  * ShoppingMix.usagemodel

**Comment by mazkatli** [comment]
The requested changes are done.

**Review by seiferma — APPROVED** [review]
Looks good to me now.

**Pull request merged**
